{
 "title": "New dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ticker",
    "label": "Ticker_Symbol",
    "query": "SELECT DISTINCT ticker_symbol FROM stocks_prices_historical ORDER BY ticker_symbol;"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Price Of the Stock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT close_price\nFROM stocks_prices_historical\nWHERE ticker_symbol = '${ticker:raw}' AND $__timeFilter(timestamp_utc)\nORDER BY timestamp_utc DESC LIMIT  1;\n\n"
    }
   ]
  },
  {
   "title": "52-Week High",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(high_price) AS \"52_week_high\"\nFROM stocks_prices_historical \nWHERE ticker_symbol='${ticker:raw}' AND \ntimestamp_utc >= now() - interval '52 weeks' AND timestamp_utc <= now();"
    }
   ]
  },
  {
   "title": "52-Week Low",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    MIN(low_price) AS \"52_week_low\"\nFROM\n    public.stocks_prices_historical\nWHERE\n    ticker_symbol = '${ticker:raw}' AND\n    timestamp_utc >= now() - interval '52 weeks' AND\n    timestamp_utc <= now();"
    }
   ]
  },
  {
   "title": "Stock Price & SMAs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_utc AS \"time\",\n  close_price,\n  open_price,\n  AVG(close_price) OVER (PARTITION BY ticker_symbol ORDER BY timestamp_utc ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS sma_20,\n  AVG(close_price) OVER (PARTITION BY ticker_symbol ORDER BY timestamp_utc ROWS BETWEEN 49 PRECEDING AND CURRENT ROW) AS sma_50\nFROM\n  public.stocks_prices_historical\nWHERE\n  ticker_symbol = '${ticker:raw}' AND\n  $__timeFilter(timestamp_utc)\nORDER BY\n  timestamp_utc ASC;"
    }
   ]
  },
  {
   "title": "Trading Volume Chart",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_utc AS \"time\",\n  volume\nFROM\n  public.stocks_prices_historical\nWHERE\n  ticker_symbol = '${ticker:raw}' AND\n  $__timeFilter(timestamp_utc)\nORDER BY\n  timestamp_utc ASC;"
    }
   ]
  }
 ]
}